-- =========================================================
-- FixFlow · V2 · Datos de demostración
-- Contraseña de todos los usuarios de demo: Demo1234!
-- Las fechas son relativas a now() para que la demo parezca siempre actual.
-- =========================================================

INSERT INTO usuario (id, nombre, email, password_hash, rol) VALUES
  (1, 'Carmen Ortiz', 'admin@fixflow.demo', '$2a$10$sbTy4KiC7ZxO33Do4UE5S.UBJ4woZFh.GYSCE5IQS4leds5XFE8ka', 'ADMIN'),
  (2, 'Antonio Ruiz', 'antonio@fixflow.demo', '$2a$10$sbTy4KiC7ZxO33Do4UE5S.UBJ4woZFh.GYSCE5IQS4leds5XFE8ka', 'TECNICO'),
  (3, 'Marta Sánchez', 'marta@fixflow.demo', '$2a$10$sbTy4KiC7ZxO33Do4UE5S.UBJ4woZFh.GYSCE5IQS4leds5XFE8ka', 'TECNICO'),
  (4, 'David Moreno', 'david@fixflow.demo', '$2a$10$sbTy4KiC7ZxO33Do4UE5S.UBJ4woZFh.GYSCE5IQS4leds5XFE8ka', 'TECNICO');

INSERT INTO cliente (id, nombre, telefono, email, creado_en) VALUES
  (1, 'José Luis Fernández', '612 345 781', 'joseluis.fdez@gmail.com', now() - interval '200 days'),
  (2, 'María del Mar Jiménez', '634 118 902', 'mdmjimenez@hotmail.com', now() - interval '188 days'),
  (3, 'Francisco Javier López', '655 207 443', NULL, now() - interval '176 days'),
  (4, 'Lucía Martín Castro', '678 902 115', 'lucia.martin.c@gmail.com', now() - interval '164 days'),
  (5, 'Rafael Navarro', '691 334 870', NULL, now() - interval '152 days'),
  (6, 'Ana Belén Gil', '622 781 054', 'anabelen.gil@outlook.es', now() - interval '140 days'),
  (7, 'Manuel Torres Vega', '647 559 218', 'm.torresvega@gmail.com', now() - interval '128 days'),
  (8, 'Cristina Romero', '619 443 687', NULL, now() - interval '116 days'),
  (9, 'Pablo Domínguez', '683 120 994', 'pablodominguez95@gmail.com', now() - interval '104 days'),
  (10, 'Isabel Guerrero', '656 872 301', 'isa.guerrero@yahoo.es', now() - interval '92 days'),
  (11, 'Academia Sur Formación', '952 48 17 63', 'info@academiasur.es', now() - interval '80 days'),
  (12, 'Sergio Molina', '605 218 776', NULL, now() - interval '68 days');

INSERT INTO equipo (id, cliente_id, tipo, marca, modelo, numero_serie) VALUES
  (1, 1, 'PORTATIL', 'Acer', 'Aspire 5 A515-57', 'NXK3LEB00123'),
  (2, 2, 'PORTATIL', 'HP', 'Pavilion 15-eg2000', '5CD2143XYZ'),
  (3, 3, 'SOBREMESA', 'Clónico', 'Torre Ryzen 5 5600 / RTX 3060', NULL),
  (4, 4, 'MOVIL', 'Apple', 'iPhone 12', 'F17DQ2ABCD12'),
  (5, 5, 'PORTATIL', 'Lenovo', 'IdeaPad 3 15ITL6', 'PF3A9KLM'),
  (6, 6, 'MOVIL', 'Samsung', 'Galaxy A52', 'R58R41ABC'),
  (7, 7, 'PORTATIL', 'MSI', 'Katana GF66', 'K2204N0012'),
  (8, 8, 'TABLET', 'Apple', 'iPad 9ª generación', 'DMPH12ABQ1'),
  (9, 9, 'PORTATIL', 'ASUS', 'VivoBook 15 X1504', 'N6NRCV01X'),
  (10, 10, 'SOBREMESA', 'HP', 'ProDesk 400 G7', 'CZC1234LMN'),
  (11, 11, 'PORTATIL', 'Dell', 'Latitude 5420', '7HJK2L3'),
  (12, 11, 'PORTATIL', 'Dell', 'Latitude 5420', '9QWE4R5'),
  (13, 12, 'MOVIL', 'Xiaomi', 'Redmi Note 11', NULL),
  (14, 1, 'MOVIL', 'Samsung', 'Galaxy S21', 'R5CR10XYZ'),
  (15, 4, 'PORTATIL', 'Apple', 'MacBook Air M1', 'FVFD1234Q6L4');

INSERT INTO reparacion (id, codigo, equipo_id, tecnico_id, averia_descrita, diagnostico, estado, presupuesto, presupuesto_aceptado, precio_final, fecha_entrada, fecha_listo, fecha_entrega) VALUES
  (1, 'FX-2026-00001', 1, 2, 'Se derramó café sobre el teclado y ahora no enciende.', 'Placa con corrosión en la zona de alimentación. Limpieza por ultrasonidos y sustitución de teclado.', 'ENTREGADO', 145, TRUE, 145, now() - interval '4084 hours', now() - interval '4084 hours' + interval '72 hours', now() - interval '4084 hours' + interval '144 hours'),
  (2, 'FX-2026-00002', 2, 3, 'Va muy lento, tarda varios minutos en arrancar.', 'Disco mecánico con sectores dañados. Cambio a SSD 500 GB y clonado del sistema.', 'ENTREGADO', 89, TRUE, 89, now() - interval '3845 hours', now() - interval '3845 hours' + interval '30 hours', now() - interval '3845 hours' + interval '72 hours'),
  (3, 'FX-2026-00003', 3, 4, 'Se apaga solo cuando juego a los 10-15 minutos.', 'Temperaturas de CPU a 95 °C. Limpieza completa y cambio de pasta térmica.', 'ENTREGADO', 45, TRUE, 45, now() - interval '3606 hours', now() - interval '3606 hours' + interval '39 hours', now() - interval '3606 hours' + interval '48 hours'),
  (4, 'FX-2026-00004', 4, 3, 'Pantalla rota tras una caída.', 'Cristal y panel OLED dañados. Sustitución de pantalla completa.', 'ENTREGADO', 189, TRUE, 189, now() - interval '3367 hours', now() - interval '3367 hours' + interval '66 hours', now() - interval '3367 hours' + interval '96 hours'),
  (5, 'FX-2026-00005', 5, 2, 'Salen anuncios en el navegador y se abren páginas solas.', 'Adware y extensiones maliciosas. Limpieza y revisión de seguridad.', 'ENTREGADO', 35, TRUE, 35, now() - interval '3080 hours', now() - interval '3080 hours' + interval '21 hours', now() - interval '3080 hours' + interval '24 hours'),
  (6, 'FX-2026-00006', 6, 4, 'No carga, hay que mover el cable para que cargue.', 'Conector USB-C desgastado. Sustitución del puerto de carga.', 'ENTREGADO', 59, TRUE, 59, now() - interval '2769 hours', now() - interval '2769 hours' + interval '59 hours', now() - interval '2769 hours' + interval '72 hours'),
  (7, 'FX-2026-00007', 7, 2, 'El ventilador hace mucho ruido.', 'Ventilador con holgura en el eje. Sustitución de ventilador y limpieza.', 'ENTREGADO', 65, TRUE, 65, now() - interval '2434 hours', now() - interval '2434 hours' + interval '113 hours', now() - interval '2434 hours' + interval '120 hours'),
  (8, 'FX-2026-00008', 8, 3, 'La batería dura menos de una hora.', 'Batería al 61 % de salud. Presupuesto de cambio de batería.', 'ENTREGADO', 99, FALSE, 15, now() - interval '2211 hours', now() - interval '2211 hours' + interval '91 hours', now() - interval '2211 hours' + interval '96 hours'),
  (9, 'FX-2026-00009', 9, 4, 'Quiere instalar Windows 11 y pasar sus fotos del equipo antiguo.', 'Instalación limpia de Windows 11, drivers y migración de datos.', 'ENTREGADO', 60, TRUE, 60, now() - interval '1924 hours', now() - interval '1924 hours' + interval '23 hours', now() - interval '1924 hours' + interval '48 hours'),
  (10, 'FX-2026-00010', 10, 2, 'No da imagen, se encienden los ventiladores pero la pantalla queda en negro.', 'Módulo de RAM defectuoso. Sustitución por módulo de 8 GB.', 'ENTREGADO', 55, TRUE, 55, now() - interval '1589 hours', now() - interval '1589 hours' + interval '50 hours', now() - interval '1589 hours' + interval '72 hours'),
  (11, 'FX-2026-00011', 11, 3, 'Bisagra rota, la pantalla no se sujeta.', 'Bisagra izquierda partida y anclaje de la carcasa dañado.', 'ENTREGADO', 75, TRUE, 75, now() - interval '1254 hours', now() - interval '1254 hours' + interval '156 hours', now() - interval '1254 hours' + interval '168 hours'),
  (12, 'FX-2026-00012', 12, 4, 'Revisión y mantenimiento antes de dárselo a un nuevo empleado.', 'Limpieza, actualización de BIOS y reinstalación del sistema.', 'ENTREGADO', 50, TRUE, 50, now() - interval '967 hours', now() - interval '967 hours' + interval '36 hours', now() - interval '967 hours' + interval '48 hours'),
  (13, 'FX-2026-00013', 13, 2, 'El móvil se ha mojado en la playa.', 'Daños por líquido en placa. Limpieza; no se garantiza la recuperación.', 'ENTREGADO', 70, TRUE, 70, now() - interval '728 hours', now() - interval '728 hours' + interval '72 hours', now() - interval '728 hours' + interval '120 hours'),
  (14, 'FX-2026-00014', 14, 3, 'No le funciona el altavoz en las llamadas.', 'Altavoz auricular obstruido y dañado. Sustitución.', 'LISTO', 49, TRUE, 49, now() - interval '297 hours', now() - interval '297 hours' + interval '96 hours', NULL),
  (15, 'FX-2026-00015', 15, 4, 'El teclado tiene varias teclas que no responden.', 'Teclado dañado. Sustitución del top case completo.', 'ESPERANDO_APROBACION', 229, NULL, NULL, now() - interval '154 hours', NULL, NULL),
  (16, 'FX-2026-00016', 2, 3, 'La tecla de encendido se ha hundido.', 'Pulsador de encendido roto en el top case.', 'EN_REPARACION', 40, TRUE, NULL, now() - interval '123 hours', NULL, NULL),
  (17, 'FX-2026-00017', 5, 2, 'Se ha vuelto a llenar de publicidad.', 'Reinfección desde una extensión sincronizada con el navegador.', 'EN_REPARACION', 35, TRUE, NULL, now() - interval '76 hours', NULL, NULL),
  (18, 'FX-2026-00018', 7, 2, 'Pantalla con una línea vertical rosa.', NULL, 'DIAGNOSTICO', NULL, NULL, NULL, now() - interval '53 hours', NULL, NULL),
  (19, 'FX-2026-00019', 3, 4, 'Quiere ampliar a 32 GB de RAM y un segundo SSD.', NULL, 'DIAGNOSTICO', NULL, NULL, NULL, now() - interval '30 hours', NULL, NULL),
  (20, 'FX-2026-00020', 9, NULL, 'No se conecta al wifi después de una actualización.', NULL, 'RECIBIDO', NULL, NULL, NULL, now() - interval '7 hours', NULL, NULL),
  (21, 'FX-2026-00021', 6, NULL, 'La cámara trasera no enfoca.', NULL, 'RECIBIDO', NULL, NULL, NULL, now() - interval '8 hours', NULL, NULL);

INSERT INTO historial_estado (reparacion_id, estado_anterior, estado_nuevo, usuario_id, comentario, fecha) VALUES
  (1, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '4084 hours' + interval '0 hours'),
  (1, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '4084 hours' + interval '8 hours'),
  (1, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '4084 hours' + interval '30 hours'),
  (1, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '4084 hours' + interval '64 hours'),
  (1, 'EN_REPARACION', 'LISTO', 2, NULL, now() - interval '4084 hours' + interval '72 hours'),
  (1, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '4084 hours' + interval '144 hours'),
  (2, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '3845 hours' + interval '0 hours'),
  (2, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '3845 hours' + interval '13 hours'),
  (2, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '3845 hours' + interval '15 hours'),
  (2, 'ESPERANDO_APROBACION', 'EN_REPARACION', 3, 'Presupuesto aceptado por el cliente', now() - interval '3845 hours' + interval '19 hours'),
  (2, 'EN_REPARACION', 'LISTO', 3, NULL, now() - interval '3845 hours' + interval '30 hours'),
  (2, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '3845 hours' + interval '72 hours'),
  (3, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '3606 hours' + interval '0 hours'),
  (3, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '3606 hours' + interval '3 hours'),
  (3, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 4, 'Presupuesto enviado al cliente', now() - interval '3606 hours' + interval '4 hours'),
  (3, 'ESPERANDO_APROBACION', 'EN_REPARACION', 4, 'Presupuesto aceptado por el cliente', now() - interval '3606 hours' + interval '29 hours'),
  (3, 'EN_REPARACION', 'LISTO', 4, NULL, now() - interval '3606 hours' + interval '39 hours'),
  (3, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '3606 hours' + interval '48 hours'),
  (4, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '3367 hours' + interval '0 hours'),
  (4, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '3367 hours' + interval '13 hours'),
  (4, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '3367 hours' + interval '29 hours'),
  (4, 'ESPERANDO_APROBACION', 'EN_REPARACION', 3, 'Presupuesto aceptado por el cliente', now() - interval '3367 hours' + interval '31 hours'),
  (4, 'EN_REPARACION', 'LISTO', 3, NULL, now() - interval '3367 hours' + interval '66 hours'),
  (4, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '3367 hours' + interval '96 hours'),
  (5, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '3080 hours' + interval '0 hours'),
  (5, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '3080 hours' + interval '2 hours'),
  (5, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '3080 hours' + interval '8 hours'),
  (5, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '3080 hours' + interval '19 hours'),
  (5, 'EN_REPARACION', 'LISTO', 2, NULL, now() - interval '3080 hours' + interval '21 hours'),
  (5, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '3080 hours' + interval '24 hours'),
  (6, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '2769 hours' + interval '0 hours'),
  (6, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '2769 hours' + interval '30 hours'),
  (6, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 4, 'Presupuesto enviado al cliente', now() - interval '2769 hours' + interval '37 hours'),
  (6, 'ESPERANDO_APROBACION', 'EN_REPARACION', 4, 'Presupuesto aceptado por el cliente', now() - interval '2769 hours' + interval '55 hours'),
  (6, 'EN_REPARACION', 'LISTO', 4, NULL, now() - interval '2769 hours' + interval '59 hours'),
  (6, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '2769 hours' + interval '72 hours'),
  (7, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '2434 hours' + interval '0 hours'),
  (7, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '2434 hours' + interval '2 hours'),
  (7, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '2434 hours' + interval '99 hours'),
  (7, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '2434 hours' + interval '105 hours'),
  (7, 'EN_REPARACION', 'LISTO', 2, NULL, now() - interval '2434 hours' + interval '113 hours'),
  (7, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '2434 hours' + interval '120 hours'),
  (8, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '2211 hours' + interval '0 hours'),
  (8, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '2211 hours' + interval '22 hours'),
  (8, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '2211 hours' + interval '56 hours'),
  (8, 'ESPERANDO_APROBACION', 'LISTO', 3, 'El cliente rechaza el presupuesto; se devuelve sin reparar', now() - interval '2211 hours' + interval '91 hours'),
  (8, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '2211 hours' + interval '96 hours'),
  (9, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '1924 hours' + interval '0 hours'),
  (9, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '1924 hours' + interval '11 hours'),
  (9, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 4, 'Presupuesto enviado al cliente', now() - interval '1924 hours' + interval '15 hours'),
  (9, 'ESPERANDO_APROBACION', 'EN_REPARACION', 4, 'Presupuesto aceptado por el cliente', now() - interval '1924 hours' + interval '19 hours'),
  (9, 'EN_REPARACION', 'LISTO', 4, NULL, now() - interval '1924 hours' + interval '23 hours'),
  (9, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '1924 hours' + interval '48 hours'),
  (10, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '1589 hours' + interval '0 hours'),
  (10, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '1589 hours' + interval '13 hours'),
  (10, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '1589 hours' + interval '15 hours'),
  (10, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '1589 hours' + interval '45 hours'),
  (10, 'EN_REPARACION', 'LISTO', 2, NULL, now() - interval '1589 hours' + interval '50 hours'),
  (10, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '1589 hours' + interval '72 hours'),
  (11, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '1254 hours' + interval '0 hours'),
  (11, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '1254 hours' + interval '26 hours'),
  (11, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '1254 hours' + interval '90 hours'),
  (11, 'ESPERANDO_APROBACION', 'EN_REPARACION', 3, 'Presupuesto aceptado por el cliente', now() - interval '1254 hours' + interval '93 hours'),
  (11, 'EN_REPARACION', 'LISTO', 3, NULL, now() - interval '1254 hours' + interval '156 hours'),
  (11, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '1254 hours' + interval '168 hours'),
  (12, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '967 hours' + interval '0 hours'),
  (12, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '967 hours' + interval '4 hours'),
  (12, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 4, 'Presupuesto enviado al cliente', now() - interval '967 hours' + interval '18 hours'),
  (12, 'ESPERANDO_APROBACION', 'EN_REPARACION', 4, 'Presupuesto aceptado por el cliente', now() - interval '967 hours' + interval '31 hours'),
  (12, 'EN_REPARACION', 'LISTO', 4, NULL, now() - interval '967 hours' + interval '36 hours'),
  (12, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '967 hours' + interval '48 hours'),
  (13, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '728 hours' + interval '0 hours'),
  (13, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '728 hours' + interval '12 hours'),
  (13, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '728 hours' + interval '17 hours'),
  (13, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '728 hours' + interval '50 hours'),
  (13, 'EN_REPARACION', 'LISTO', 2, NULL, now() - interval '728 hours' + interval '72 hours'),
  (13, 'LISTO', 'ENTREGADO', 1, 'Entregado al cliente', now() - interval '728 hours' + interval '120 hours'),
  (14, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '297 hours' + interval '0 hours'),
  (14, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '297 hours' + interval '39 hours'),
  (14, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '297 hours' + interval '81 hours'),
  (14, 'ESPERANDO_APROBACION', 'EN_REPARACION', 3, 'Presupuesto aceptado por el cliente', now() - interval '297 hours' + interval '82 hours'),
  (14, 'EN_REPARACION', 'LISTO', 3, NULL, now() - interval '297 hours' + interval '96 hours'),
  (15, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '154 hours' + interval '0 hours'),
  (15, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '154 hours' + interval '51 hours'),
  (15, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 4, 'Presupuesto enviado al cliente', now() - interval '154 hours' + interval '102 hours'),
  (16, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '123 hours' + interval '0 hours'),
  (16, 'RECIBIDO', 'DIAGNOSTICO', 3, NULL, now() - interval '123 hours' + interval '30 hours'),
  (16, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 3, 'Presupuesto enviado al cliente', now() - interval '123 hours' + interval '60 hours'),
  (16, 'ESPERANDO_APROBACION', 'EN_REPARACION', 3, 'Presupuesto aceptado por el cliente', now() - interval '123 hours' + interval '90 hours'),
  (17, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '76 hours' + interval '0 hours'),
  (17, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '76 hours' + interval '18 hours'),
  (17, 'DIAGNOSTICO', 'ESPERANDO_APROBACION', 2, 'Presupuesto enviado al cliente', now() - interval '76 hours' + interval '36 hours'),
  (17, 'ESPERANDO_APROBACION', 'EN_REPARACION', 2, 'Presupuesto aceptado por el cliente', now() - interval '76 hours' + interval '54 hours'),
  (18, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '53 hours' + interval '0 hours'),
  (18, 'RECIBIDO', 'DIAGNOSTICO', 2, NULL, now() - interval '53 hours' + interval '26 hours'),
  (19, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '30 hours' + interval '0 hours'),
  (19, 'RECIBIDO', 'DIAGNOSTICO', 4, NULL, now() - interval '30 hours' + interval '14 hours'),
  (20, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '7 hours' + interval '0 hours'),
  (21, NULL, 'RECIBIDO', 1, 'Equipo recibido en mostrador', now() - interval '8 hours' + interval '0 hours');

-- Como los ids se han puesto a mano, se sincronizan las secuencias
SELECT setval('usuario_id_seq', (SELECT max(id) FROM usuario));
SELECT setval('cliente_id_seq', (SELECT max(id) FROM cliente));
SELECT setval('equipo_id_seq', (SELECT max(id) FROM equipo));
SELECT setval('reparacion_id_seq', (SELECT max(id) FROM reparacion));
SELECT setval('reparacion_codigo_seq', 21);
